apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app-1
  labels:
    app: cicd-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-app-1
  template:
    metadata:
      labels:
        app: cicd-app-1
    spec:
      containers:
      - name: cicd-app-1
        image: gcr.io/devops-442409/gke-image:v3.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"